### ISSUE TITLE
Comma should be ignored inside quoted text

### ISSUE THREAD

**Issue by bradvogel** [nepsilon/search-query-parser#16]
The example:
`require('search-query-parser').parse('test from:"one,two"',{keywords: ['from']})`
returns two values, eg `from: [ 'one', 'two' ],`

I'd think `"one,two"` should be treated as one word, so it should return `from: [ 'one,two' ],`

**Comment by nepsilon** [comment]
I think the current output is the most expected. The comma is an item delimiter.

To make it work the way you want we could escape the comma (either programmatically or by telling the user):

```javascript
require('search-query-parser').parse('test from:"one\,two"', {keywords: ['from']})
```

**Comment by bradvogel** [comment]
It seems clearer to me that anything inside of quotes is automatically escaped (except other quotes of course). So double quotes always have precedence.

So the following would the true:
`from:one,two` -> `from: ["one", "two"]`
`from:one\,two` -> `from: ["one,two"]`
`from:"one,two"` -> `from: ["one,two"]`
`from:"one\,two"` -> `from: ["one,two"]`

**Comment by bradvogel** [comment]
Here's a PR: https://github.com/nepsilon/search-query-parser/pull/17

**Comment by nepsilon** [comment]
That works too. We can use the quotes to mean "one item" and the comma as a separator.  We'd need exhaustive test coverage for this though. Let's follow up on the PR.

And thanks for the PR 👍

**Comment by bradvogel** [comment]
fyi, we just released https://github.com/mixmaxhq/search-string that fixes this
