### ISSUE TITLE
Difference to other libraries

### ISSUE THREAD

**Issue by laggingreflex** [nepsilon/search-query-parser#24]
Was looking for something exactly like this, and came across a few others:

https://github.com/mixmaxhq/search-string

Both look equally good at first glance, which makes it difficult to choose... it'd be awesome if there were some comparison between features/goals

[](https://github.com/mixmaxhq/search-string/issues/24)

**Comment by nepsilon** [comment]
Hi, not too sure, I haven't used Mixmax lib. They used my lib at first, but then recoded it to fit their specific use cases (I understand). Maybe check with them what they did differently?

On specificity of this lib is I put a lot of attention at having good and up to date unit tests.
