### ISSUE TITLE
Behavior of parser when no keywords are present

### ISSUE THREAD

**Issue by wdhorton** [nepsilon/search-query-parser#3]
First of all, this library is so useful! Thank you. Just wanted to point out one behavior that's not clearly documented: when no keywords are included in the query, `searchQuery.parse()` just returns the query itself. I see that it's commented in the source code, but I'd be happy to submit a PR to the README to make it more obvious.

**Comment by nepsilon** [comment]
Hi @wdhorton, thanks for proposing to contribute! Your PR is very welcome :+1:

**Comment by wdhorton** [comment]
PR #4 is submitted!

**Comment by nepsilon** [comment]
Thanks @wdhorton! Your PR is merged :+1:

**Comment by wdhorton** [comment]
Cool! Let me know if there's any more work you'd like to see done on this.
