### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by satazor** [nepsilon/search-query-parser#7]
The master branch contains a fix and some improvements that I would like to have on npm. Also could you please bump this to `1.0.0`? I'm going to use this module in https://npms.io

**Comment by nepsilon** [comment]
[Done](https://www.npmjs.com/package/search-query-parser)! 

Looking forward to use it on [npms.io](https://npms.io) 👍

**Comment by satazor** [comment]
Ty!
