### ISSUE TITLE
API

### ISSUE THREAD

**Issue by satazor** [nepsilon/search-query-parser#8]
As I said in #7, I'm trying to use this in npms.io. 

One minor thing that I think it could be improved: Always return an object even if there's nothing to be parsed. At the moment I need to do something like `query = typeof query === 'string' ? { text: query } : query;`

Thoughts?

**Comment by nepsilon** [comment]
I won't be able to code this in the short term. But I'll accept a pull request with the implementation and related tests :)

**Comment by nepsilon** [comment]
@satazor Do you still need this? Or did you find a work around maybe?

**Comment by satazor** [comment]
I'm doing the mentioned workaround above. I had no time for the PR and then I totally forgot about it.

**Comment by nepsilon** [comment]
No problem. Should I close this issue?

**Comment by satazor** [comment]
Hmm I still need the return value of this module should be consistent. Since I'm overloaded with work I don't have time to do a PR. It's your call to close this issue though.

**Comment by nepsilon** [comment]
Got it. I'll keep it open for now.
